name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Patient-Care-Aggregator-Api-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }} 
    short_service_name: ${{ variables.short_service_name }} 
    service_base_path: ${{ variables.service_base_path }} 
    prod_producer_approval: true
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: ./templates/run-tests.yml
      - environment: internal-dev
        stage_name: internal-dev-alpha
        service_name: "${{ variables.service_name }}-alpha"
        short_service_name: "${{ variables.short_service_name }}-alpha"
        service_base_path: "${{ variables.service_base_path }}-alpha"
        jinja_templates:
          PCA_TARGET_SERVER: patient-care-aggregator-api-alpha
      - environment: internal-dev
        stage_name: internal-dev-nft
        service_name: "${{ variables.service_name }}-nft"
        short_service_name: "${{ variables.short_service_name }}-nft"
        service_base_path: "${{ variables.service_base_path }}-nft"
        jinja_templates:
          PCA_TARGET_SERVER: patient-care-aggregator-api-nft           
      - environment: internal-qa
        post_deploy:
          - template: ./templates/run-tests.yml
      - environment: int
        depends_on:
          - internal_qa
        post_deploy:
          - template: ./templates/run-tests.yml
      - environment: prod
        depends_on:
          - internal_qa
