# This is an OpenAPI Specification (https://swagger.io/specification/)
# for patient-care-aggregator-api owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: 'patient-care-aggregator-api'
  version: 'Computed and injected at build time by `scripts/set_version.py`'
  description: |
    ## Overview
    TBC
    
    ## Who can use this API
    TBC
    
    ## API status and roadmap
    TBC
    
    ## Service level
    TBC
    
    ## Technology
    TBC
    
    ## Network access
    TBC
    
    ## Security and authorisation
    TBC
    
    ## Environments and testing
    TBC
    
    ## Onboarding
    TBC
    
  contact:
    name: 'patient-care-aggregator-api API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/patient-care-aggregator-api'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/patient-care-aggregator-api'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/patient-care-aggregator-api'
    description: Production environment.
paths: {}
