# This is an OpenAPI Specification (https://swagger.io/specification/) 
# for patient-care-aggregator-api owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: "Patient Care Aggregator Record Service API"
  version: "1.0.0"
  description: |
    ## Overview 
    ![Patient Care Aggregator Get Appointments API Standard context diagram](https://digital.nhs.uk/binaries/content/gallery/website/developer/api-catalogue/patient-care-aggregator-fhir-api/patient-care-aggregator-record-service-api-context-diagram.svg?raw=true)

    Use this API, as a secondary care provider, to let the Patient Care Aggregator know which patients you have bookings for. 

    The Patient Care Aggregator needs this information in advance so it knows which secondary care providers to ask for a list of bookings when a patient requests the list using the NHS App. 

    As a secondary care provider, you’ll also need to: 
    - build an API using the [Patient Care Aggregator Get Applications API standard](https://digital.nhs.uk/developer/api-catalogue/patient-care-aggregator-get-appointments/patient-care-aggregator-get-appointments-api-standard) that the Patient Care Aggregator can use to get a list of bookings for a patient
    - build a ‘patient portal’ web application that the patient can access via a hyperlink from the NHS App 

    For more details, see [Building healthcare software – patient access to referrals and bookings](https://digital.nhs.uk/developer/guides-and-documentation/building-healthcare-software/referrals-and-bookings/patient-access-to-referrals-and-bookings). 

    ## Who can use this API 
    You can only use this API if you are integrating a secondary care booking system with our Patient Care Aggregator. 

    ## API status 

    This API is in [beta](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses),
    meaning it is available for use in production but might be subject to breaking changes.

    ## Service level 
    This API is a gold service, meaning it is operational and supported 24 x 7 x 365. 

    For more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels). 

    ## Technology 
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest).

    ## Network access
    This API is available on the internet and, indirectly, on the Health and Social Care Network (HSCN). 

    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis). 

    ## Security and authorisation 
    TBC app-restricted?

    ## Environments and testing 
    TBC 

    ## Onboarding 
    TBC 

  contact:
    name: 'patient-care-aggregator-api API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://tbc'
    description: Sandbox environment.
  - url: 'https://tbc'
    description: Integration test environment.
  - url: 'https://tbc'
    description: Production environment.
paths:
  /records:
    post:
      summary: TBC
      operationId: tbc
      description: |
        TBC
      parameters:
        - name: tbc
          in: query
          description: |
            TBC
          required: true
          schema:
            type: string
            example: "TBC"
      responses:
        '2XX':
          description: |
            TBC
        '4XX':
          description: |
            TBC
