# This is an OpenAPI Specification (https://swagger.io/specification/) 
# for patient-care-aggregator-api owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: "Patient Care Aggregator API"
  version: "1.0.0"
  description: |
  
    <div class="nhsd-m-emphasis-box nhsd-m-emphasis-box--emphasis nhsd-!t-margin-bottom-6" aria-label="Highlighted Information">
        <div class="nhsd-a-box nhsd-a-box--border-blue">
            <div class="nhsd-m-emphasis-box__image-box">
                <figure class="nhsd-a-image">
                    <picture class="nhsd-a-image__picture">
                        <img src="//nhs-prod.global.ssl.fastly.net/svg-magic/binaries/content/gallery/icons/info.svg?colour=231f20" alt="" style="object-fit:fill">
                    </picture>
                </figure>
            </div>
            <div class="nhsd-m-emphasis-box__content-box">
                <div data-uipath="website.contentblock.emphasis.content" class="nhsd-t-word-break"><p class="nhsd-t-body">This API is currently for internal NHS Digital use only.</p></div>            
            </div>
        </div>
    </div>
    
    ## Overview
    
    ![Patient Care Aggregator FHIR API context diagram](https://digital.nhs.uk/binaries/content/gallery/website/developer/api-catalogue/patient-care-aggregator-fhir-api/patient-care-aggregator-api-context-diagram.svg?raw=true)
    
    Use this API to get an aggregated list of referrals and bookings for a patient from secondary care providers.
    
    The API aggregates details of referrals and bookings from the following systems:
    - [NHS e-Referral Service](https://digital.nhs.uk/services/e-referral-service) (referrals and bookings)
    - [DrDoctor](https://www.drdoctor.co.uk/) (bookings only)
    - [Patients Know Best](https://patientsknowbest.com/) (bookings only)
    
    We might add other providers in the future.
    
    This API is only for use in patient-facing applications, not point-of-care applications.
    
    ## Who can use this API
    Currently, this API is for internal use only - the only API consumer is the NHS App.
    
    If you are interested in using this API in another context, [contact us](https://digital.nhs.uk/developer/help-and-support).
    
    ## API status
    This API is [in production, beta but for internal](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses) NHS Digital use only.
    
    If you would still like to be involved in our beta programme or use this API, [contact us](https://digital.nhs.uk/developer/help-and-support).
        
        ## Service level
    The [service level](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels) for this API
    is gold.
    
    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest).

    It conforms to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir)
    global standard for health care data exchange, specifically to [FHIR R4 (v4.0.1)](https://hl7.org/fhir/r4/),
    except that it does not support the [capabilities](http://hl7.org/fhir/R4/http.html#capabilities) interaction.

    It includes some country-specific FHIR extensions, which have been built against [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core).

    You do not need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules.
    In particular:
    - resource names are capitalised and singular, for example `/CarePlan` not `/care-plans`
    - array names are singular, for example `entry` not `entries` for FHIR bundle entries
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object

    There are [libraries and SDKs available](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir-libraries-and-sdks) to help with FHIR API integration.

    ## Network access
    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).

    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).
    
    ## Security and authorisation
    This API is [user-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis), meaning an end user must be present, authenticated and authorised.
    
    The end user must be:
    * a patient who receives health and social care or makes use of NHS services
    * strongly authenticated, using [NHS login](https://digital.nhs.uk/services/nhs-login)
     
    To use this API, use one of the following security patterns:
    
    |	Security pattern		                                                                                                                                                                                                          |	Technical details	                                  |	Advantages	                                                | Disadvantages                                           |
    |-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------| ----------------------------------------------------| ------------------------------------------------------------|---------------------------------------------------------|
    |[NHS login - combined authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-login-combined-authentication-and-authorisation) |OAuth 2.0 authorisation code with API key and secret |No need to integrate and onboard separately with NHS login.  |No access to user information.                           |
    |[NHS login - separate authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-login-separate-authentication-and-authorisation) |OAuth 2.0 token exchange with signed JWT             |Gives access to user information.                            |Need to integrate and onboard separately with NHS login. |
    
    ## Environments and testing
    | Environment       | Base URL                                                                        | Linked NHS login environment  |
    | ----------------- | ------------------------------------------------------------------------------- | ----------------------------- |
    | Sandbox           | Not available                                                                   | Not applicable                |
    | Integration test  | `https://int.api.service.nhs.uk/patient-care-aggregator-api/aggregator/events/` | NHS login - integration (AOS) |
    | Production        | `https://api.service.nhs.uk/patient-care-aggregator-api/aggregator/events/`     | NHS login - Live (production) |

    ### Sandbox testing
    This API does not currently have a sandbox environment. If you would like us to add one, [contact us](https://digital.nhs.uk/developer/help-and-support).
    
    ### Integration testing
    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):
    * is for formal integration testing
    * includes authorisation

    It is an end-to-end environment - it includes instances of each of the back-end applications, and is linked to the Integration (AOS) instance of NHS login.
    
    For details of test data, see [Patient care aggregator test data packs](https://digital.nhs.uk/developer/api-catalogue/patient-care-aggregator-fhir/patient-care-aggregator-fhir-api-test-data).

    For more details on integration testing, see [integration testing with our RESTful APIs](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing-with-our-restful-apis).
    
    ## Onboarding
    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it’s worth planning well ahead.
    
    To onboard for this API, follow the [Supplier Conformance Assessment List (SCAL)](https://digital.nhs.uk/developer/guides-and-documentation/onboarding-process#onboard-using-the-supplier-conformance-assessment-list-scal-process) process.
    
    To get started with the SCAL process for this API, [contact us](https://digital.nhs.uk/developer/help-and-support).
    
  contact:
    name: 'patient-care-aggregator-api API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/patient-care-aggregator-api'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/patient-care-aggregator-api'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/patient-care-aggregator-api'
    description: Production environment.
paths:
  /CarePlan:
    get:
      summary: Get referrals and bookings
      operationId: get-referrals-and-bookings
      description: |
        Use this endpoint to get an aggregated list of referrals and bookings for a patient from secondary care providers.
        The endpoint checks for referrals and bookings from multiple back-end applications and aggregates them into a single list.
        
        The endpoint returns the list as a FHIR 'bundle' which includes:
        - one `CarePlan` resource, including all referrals and bookings found for the patient, but only if any referrals or bookings were found
        - one `OperationOutcome` resource, if any of the back-end applications returned an error
        
        If no referrals or bookings were found for the patient,
        and there were no errors, the endpoint returns an empty FHIR bundle.
        
      parameters:
        - name: patient.identifier
          in: query
          description: |
            The patient's NHS number.
            Expressed as `<type>|<value>` where `<type>` must be `https://fhir.nhs.uk/Id/nhs-number` and `<value>` must be a [valid NHS number](https://www.datadictionary.nhs.uk/attributes/nhs_number.html).
          required: true
          schema:
            type: string
            example: "https://fhir.nhs.uk/Id/nhs-number|9000000009"
        - name: Authorization
          in: header
          description: |
            An OAuth 2.0 bearer token, obtained using one of the security patterns explained in the 'Security and authorisation' section above.
          required: true
          schema:
            type: string
            format: '^Bearer\ [[:ascii:]]+$'
            example: 'Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM'
        - name: X-Request-ID
          in: header
          required: false
          description: |
            A globally unique identifier (GUID) for the request, which we use to de-duplicate repeated requests and to trace the request if you contact our helpdesk.

            Must be a universally unique identifier (UUID) (ideally version 4).
            
            Not mirrored back in a response header (we might change this).
            
            If you re-send a failed request, use the same value in this header.
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
            example: 60E0B220-8136-4CA5-AE46-1D97EF59D068
        - name: X-Correlation-ID
          in: header
          required: true
          description: |
            An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters.
            
            Not mirrored back in a response header (we might change this).
          schema:
            type: string
            example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
        - name: NHSD-Target-Identifier
          in: header
          required: true
          description: |
            A unique identifier for this API, as required by the Booking and Referral Standard (BaRS). Specifically, it is a Base64 encoding of:
            
            `{ "system": "urn:ietf:rfc:3986", "value": "db71698b-cd7c-4dd5-95c4-0aa9776595f5" }`
            
            (where the GUID `db71698b-cd7c-4dd5-95c4-0aa9776595f5` is the unique identifier for this API)
          schema:
            type: string
            enum:
              - "ewrCoCDCoCAic3lzdGVtIjogInVybjppZXRmOnJmYzozOTg2IiwKwqAgwqAgInZhbHVlIjogImRiNzE2OThiLWNkN2MtNGRkNS05NWM0LTBhYTk3NzY1OTVmNSIKfQ=="
# TBC why is this even needed - seems a bit bizarre to be calling an API and including a unique ID for the thing you're calling.
# TBC discuss with Richard Ward
      responses:
        '2XX':
          description: |
            The request was valid and the API was able to request information from the various back-end applications.

            There are two possible outcomes:

            | HTTP status | Description                                                         |
            | ----------- | ------------------------------------------------------------------- |
            | 200         | All back-end systems responded normally. If any referrals or bookings were found, the response includes them all in a single `CarePlan` resource. |
            | 207         | One or more back-end systems returned an error. If any referrals or bookings were found, the response includes them all in a single `CarePlan` resource. The response also includes all the errors in a single `OperationOutcome` resource. |
            
          content:
            application/fhir+json:   
              schema:
                $ref: "components/schemas/GetCarePlanResponseHappyPath.yaml"
              examples:
                happyPath:
                  summary: "A response where all back-end systems responded normally (HTTP status 200). Contains a `CarePlan` resource containing one referral and one booking."
                  value:
                    $ref: "components/examples/GetCarePlanResponseHappyPath.json"
# TBC example shows fullUrl as 'https://servita-sandbox.co.uk/CarePlan/1' whereas on other APIs its more like a GUID                
                oneOrMoreErrors:
                  summary: "A response where one back-end system returned an error (HTTP status 207). Includes a `CarePlan` resource containing one referral and one booking, and an `OperationOutcome` resource containing one back-end system error."
                  value:
                    $ref: "components/examples/GetCarePlanResponseWithErrors.json"
        '4XX':
          description: |
            An error occurred as follows:
            
            | HTTP status | Error code          | Description                                                         |
            | ----------- | ------------------- | ------------------------------------------------------------------- |
            | 400         | `exception`         | Missing or invalid NHS number in request                            |
            | 401         | `processing`        | Missing or invalid OAuth 2.0 bearer token in request                |
            | 401         | `processing`        | NHS number in request doesn't match NHS number in NHS login account |
            | 403         | `forbidden`         | Patient is under 16 years of age                                    |
            | 404         | `not-found`         | Invalid value in `NHSD-Target-Identifier` header                    |
            | 429         | `TOO_MANY_REQUESTS` | You have exceeded your application's [rate limit](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#rate-limits). |
            
            For details see the `diagnostics` field.
            
# TBC feels like the error codes should be more specific e.g. UNDER_16_DENIED would be better as an error code, not a diagnostic code
# TBC is the input parameter an ID token or an OAuth 2.0 access token?
# TBC invalid NHS number includes the NHS number in the diagnostics - might be better not to include it
# TBC error code format for 401 errors - PDS spec says ACCESS_DENIED
# TBC Des says this is a restriction of FHIR - Daniel Lynagh has a code set
          content:
            application/fhir+json:   
              schema:
                $ref: "components/schemas/GetCarePlanResponse4xx.yaml"
              example:
                $ref: "components/examples/GetCarePlanResponse4xx.json"
        "5XX":
          description: |
            A 5xx status code means the server has a problem. For more details on the most common 5xx status codes and their meanings see the [HTTP status codes](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes).
