name: PR Quality Check
on: pull_request

jobs:
  link-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Validate branch name and Jira ticket
        id: validate
        uses: NHSDigital/patient-care-aggregator.utilities/actions/validate-branch-name@main
        with:
          branch-name: ${{ github.head_ref }}
          allowed-ticket-regex: '([Ww][Pp][Pp]-[0-9]+)'     

      # - name: Fail if validation failed
      #       if: steps.validate.outputs.validation-passed == 'false'
      #       shell: bash
      #       run: exit 1
